# This file was generated by GoReleaser. DO NOT EDIT.
class Ggvc < Formula
  desc "Generates semantic version based on the version in gradle.properties and git branch"
  homepage "https://github.com/titenkov/gradle-git-version-calculator"
  version "0.0.3"

  if OS.mac?
    url "https://github.com/titenkov/gradle-git-version-calculator/releases/download/v0.0.3/gradle-git-version-calculator_0.0.3_Darwin_x86_64.tar.gz"
    sha256 "d2c22eab32a6c42b9d93ff09256250f1904f2302bb7c143b4be30279cdddb37f"
  elsif OS.linux?
    url "https://github.com/titenkov/gradle-git-version-calculator/releases/download/v0.0.3/gradle-git-version-calculator_0.0.3_Linux_x86_64.tar.gz"
    sha256 "dd148eadba22e6b20fbe17b8666e57ef89231a67d7b353fa6903f1da280ad36d"
  end
  
  depends_on "git"

  def install
    bin.install "ggvc"
  end
end
