# This file was generated by GoReleaser. DO NOT EDIT.
class Ggvc < Formula
  desc "Generates semantic version based on the version in gradle.properties and git branch"
  homepage "https://github.com/titenkov/gradle-git-version-calculator"
  version "0.0.3"

  if OS.mac?
    url "https://github.com/titenkov/gradle-git-version-calculator/releases/download/v0.0.3/gradle-git-version-calculator_0.0.3_Darwin_x86_64.tar.gz"
    sha256 "cdbb169e1ad5d1572195465ca613cdf3fd24cfe056f27509da2f4951721f4a8c"
  elsif OS.linux?
    url "https://github.com/titenkov/gradle-git-version-calculator/releases/download/v0.0.3/gradle-git-version-calculator_0.0.3_Linux_x86_64.tar.gz"
    sha256 "e84dba8f2a3520a7c3df752e6802f3dae71b38530b313436eb4beca5fc30720f"
  end
  
  depends_on "git"

  def install
    bin.install "ggvc"
  end
end
