# This file was generated by GoReleaser. DO NOT EDIT.
class Ggvc < Formula
  desc "Generates semantic version based on the version in gradle.properties and git branch"
  homepage "https://github.com/titenkov/gradle-git-version-calculator"
  version "0.0.3"

  if OS.mac?
    url "https://github.com/titenkov/gradle-git-version-calculator/releases/download/v0.0.3/gradle-git-version-calculator_0.0.3_Darwin_x86_64.tar.gz"
    sha256 "c7e0fc3eea558cd01d130723a7aec226e91d22ba74edd3a7b44154e90b7e9a92"
  elsif OS.linux?
    url "https://github.com/titenkov/gradle-git-version-calculator/releases/download/v0.0.3/gradle-git-version-calculator_0.0.3_Linux_x86_64.tar.gz"
    sha256 "e7b77c034027be809e80a711203aac453715c5dd29e5f2ea07ebdbdb7d969a9d"
  end
  
  depends_on "git"

  def install
    bin.install "ggvc"
  end
end
